[package]
name = "axum_poll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.2.8"
dotenv = "0.15.0"
parking_lot = "0.11.2"
sailfish = "0.3.3"
serde = { version = "1.0.130", features = ["derive"] }
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "sqlite"] }
structopt = "0.3.25"
tokio = { version = "1.13.0", features = ["full", "tracing"] }
tower = { version = "0.4.10", features = ["util", "timeout"] }
tower-http = { version = "0.1.1", features = ["add-extension", "trace"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
