[package]
name = "axum_poll"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.2.8"
sailfish = "0.3.3"
serde = { version = "1.0.130", features = ["derive"] }
sqlx = { version = "0.5.9", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1.13.0", features = ["full", "tracing"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.1"
